[package]
name = "debugdumpgen"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13"
bevy_mod_debugdump = "0.10"
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "s"
lto = "thin"
strip = true
